//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace OneStop.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string str_LastTronDirectory {
            get {
                return ((string)(this["str_LastTronDirectory"]));
            }
            set {
                this["str_LastTronDirectory"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string str_StoredApps {
            get {
                return ((string)(this["str_StoredApps"]));
            }
            set {
                this["str_StoredApps"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("SuperShop")]
        public string str_Shop_Name {
            get {
                return ((string)(this["str_Shop_Name"]));
            }
            set {
                this["str_Shop_Name"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("204 N. Street St.")]
        public string str_Shop_Addr1 {
            get {
                return ((string)(this["str_Shop_Addr1"]));
            }
            set {
                this["str_Shop_Addr1"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Upper Level Suite A")]
        public string str_Shop_Addr2 {
            get {
                return ((string)(this["str_Shop_Addr2"]));
            }
            set {
                this["str_Shop_Addr2"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("555-867-5309")]
        public string str_Shop_Phone {
            get {
                return ((string)(this["str_Shop_Phone"]));
            }
            set {
                this["str_Shop_Phone"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("support@supershop.net")]
        public string str_Shop_Email {
            get {
                return ((string)(this["str_Shop_Email"]));
            }
            set {
                this["str_Shop_Email"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Anytown")]
        public string str_Shop_City {
            get {
                return ((string)(this["str_Shop_City"]));
            }
            set {
                this["str_Shop_City"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Illinois")]
        public string str_Shop_State {
            get {
                return ((string)(this["str_Shop_State"]));
            }
            set {
                this["str_Shop_State"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_a {
            get {
                return ((bool)(this["bool_tron_a"]));
            }
            set {
                this["bool_tron_a"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_c {
            get {
                return ((bool)(this["bool_tron_c"]));
            }
            set {
                this["bool_tron_c"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_d {
            get {
                return ((bool)(this["bool_tron_d"]));
            }
            set {
                this["bool_tron_d"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_dev {
            get {
                return ((bool)(this["bool_tron_dev"]));
            }
            set {
                this["bool_tron_dev"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_e {
            get {
                return ((bool)(this["bool_tron_e"]));
            }
            set {
                this["bool_tron_e"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_er {
            get {
                return ((bool)(this["bool_tron_er"]));
            }
            set {
                this["bool_tron_er"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_m {
            get {
                return ((bool)(this["bool_tron_m"]));
            }
            set {
                this["bool_tron_m"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_o {
            get {
                return ((bool)(this["bool_tron_o"]));
            }
            set {
                this["bool_tron_o"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_p {
            get {
                return ((bool)(this["bool_tron_p"]));
            }
            set {
                this["bool_tron_p"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_r {
            get {
                return ((bool)(this["bool_tron_r"]));
            }
            set {
                this["bool_tron_r"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_sa {
            get {
                return ((bool)(this["bool_tron_sa"]));
            }
            set {
                this["bool_tron_sa"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_sb {
            get {
                return ((bool)(this["bool_tron_sb"]));
            }
            set {
                this["bool_tron_sb"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_sd {
            get {
                return ((bool)(this["bool_tron_sd"]));
            }
            set {
                this["bool_tron_sd"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_sdc {
            get {
                return ((bool)(this["bool_tron_sdc"]));
            }
            set {
                this["bool_tron_sdc"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_se {
            get {
                return ((bool)(this["bool_tron_se"]));
            }
            set {
                this["bool_tron_se"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_sfr {
            get {
                return ((bool)(this["bool_tron_sfr"]));
            }
            set {
                this["bool_tron_sfr"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_sk {
            get {
                return ((bool)(this["bool_tron_sk"]));
            }
            set {
                this["bool_tron_sk"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_sm {
            get {
                return ((bool)(this["bool_tron_sm"]));
            }
            set {
                this["bool_tron_sm"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_sp {
            get {
                return ((bool)(this["bool_tron_sp"]));
            }
            set {
                this["bool_tron_sp"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_spr {
            get {
                return ((bool)(this["bool_tron_spr"]));
            }
            set {
                this["bool_tron_spr"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_srr {
            get {
                return ((bool)(this["bool_tron_srr"]));
            }
            set {
                this["bool_tron_srr"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_ss {
            get {
                return ((bool)(this["bool_tron_ss"]));
            }
            set {
                this["bool_tron_ss"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_str {
            get {
                return ((bool)(this["bool_tron_str"]));
            }
            set {
                this["bool_tron_str"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_sw {
            get {
                return ((bool)(this["bool_tron_sw"]));
            }
            set {
                this["bool_tron_sw"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_v {
            get {
                return ((bool)(this["bool_tron_v"]));
            }
            set {
                this["bool_tron_v"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool bool_tron_x {
            get {
                return ((bool)(this["bool_tron_x"]));
            }
            set {
                this["bool_tron_x"] = value;
            }
        }
    }
}
