//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneStop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_LastTronDirectory {
            get {
                return ((string)(this["str_LastTronDirectory"]));
            }
            set {
                this["str_LastTronDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string str_StoredApps {
            get {
                return ((string)(this["str_StoredApps"]));
            }
            set {
                this["str_StoredApps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SuperShop")]
        public string str_Shop_Name {
            get {
                return ((string)(this["str_Shop_Name"]));
            }
            set {
                this["str_Shop_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204 N. Street St.")]
        public string str_Shop_Addr1 {
            get {
                return ((string)(this["str_Shop_Addr1"]));
            }
            set {
                this["str_Shop_Addr1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Upper Level Suite A")]
        public string str_Shop_Addr2 {
            get {
                return ((string)(this["str_Shop_Addr2"]));
            }
            set {
                this["str_Shop_Addr2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("555-867-5309")]
        public string str_Shop_Phone {
            get {
                return ((string)(this["str_Shop_Phone"]));
            }
            set {
                this["str_Shop_Phone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("support@supershop.net")]
        public string str_Shop_Email {
            get {
                return ((string)(this["str_Shop_Email"]));
            }
            set {
                this["str_Shop_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Anytown")]
        public string str_Shop_City {
            get {
                return ((string)(this["str_Shop_City"]));
            }
            set {
                this["str_Shop_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Illinois")]
        public string str_Shop_State {
            get {
                return ((string)(this["str_Shop_State"]));
            }
            set {
                this["str_Shop_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_a {
            get {
                return ((bool)(this["bool_tron_a"]));
            }
            set {
                this["bool_tron_a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_c {
            get {
                return ((bool)(this["bool_tron_c"]));
            }
            set {
                this["bool_tron_c"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_d {
            get {
                return ((bool)(this["bool_tron_d"]));
            }
            set {
                this["bool_tron_d"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_dev {
            get {
                return ((bool)(this["bool_tron_dev"]));
            }
            set {
                this["bool_tron_dev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_e {
            get {
                return ((bool)(this["bool_tron_e"]));
            }
            set {
                this["bool_tron_e"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_er {
            get {
                return ((bool)(this["bool_tron_er"]));
            }
            set {
                this["bool_tron_er"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_m {
            get {
                return ((bool)(this["bool_tron_m"]));
            }
            set {
                this["bool_tron_m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_o {
            get {
                return ((bool)(this["bool_tron_o"]));
            }
            set {
                this["bool_tron_o"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_p {
            get {
                return ((bool)(this["bool_tron_p"]));
            }
            set {
                this["bool_tron_p"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_r {
            get {
                return ((bool)(this["bool_tron_r"]));
            }
            set {
                this["bool_tron_r"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_sa {
            get {
                return ((bool)(this["bool_tron_sa"]));
            }
            set {
                this["bool_tron_sa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_sb {
            get {
                return ((bool)(this["bool_tron_sb"]));
            }
            set {
                this["bool_tron_sb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_sd {
            get {
                return ((bool)(this["bool_tron_sd"]));
            }
            set {
                this["bool_tron_sd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_sdc {
            get {
                return ((bool)(this["bool_tron_sdc"]));
            }
            set {
                this["bool_tron_sdc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_se {
            get {
                return ((bool)(this["bool_tron_se"]));
            }
            set {
                this["bool_tron_se"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_sfr {
            get {
                return ((bool)(this["bool_tron_sfr"]));
            }
            set {
                this["bool_tron_sfr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_sk {
            get {
                return ((bool)(this["bool_tron_sk"]));
            }
            set {
                this["bool_tron_sk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_sm {
            get {
                return ((bool)(this["bool_tron_sm"]));
            }
            set {
                this["bool_tron_sm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_sp {
            get {
                return ((bool)(this["bool_tron_sp"]));
            }
            set {
                this["bool_tron_sp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_spr {
            get {
                return ((bool)(this["bool_tron_spr"]));
            }
            set {
                this["bool_tron_spr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_srr {
            get {
                return ((bool)(this["bool_tron_srr"]));
            }
            set {
                this["bool_tron_srr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_ss {
            get {
                return ((bool)(this["bool_tron_ss"]));
            }
            set {
                this["bool_tron_ss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_str {
            get {
                return ((bool)(this["bool_tron_str"]));
            }
            set {
                this["bool_tron_str"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_sw {
            get {
                return ((bool)(this["bool_tron_sw"]));
            }
            set {
                this["bool_tron_sw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_v {
            get {
                return ((bool)(this["bool_tron_v"]));
            }
            set {
                this["bool_tron_v"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bool_tron_x {
            get {
                return ((bool)(this["bool_tron_x"]));
            }
            set {
                this["bool_tron_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolVerboseErrorLog {
            get {
                return ((bool)(this["boolVerboseErrorLog"]));
            }
            set {
                this["boolVerboseErrorLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolVerboseErrorConsole {
            get {
                return ((bool)(this["boolVerboseErrorConsole"]));
            }
            set {
                this["boolVerboseErrorConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolCMDLog {
            get {
                return ((bool)(this["boolCMDLog"]));
            }
            set {
                this["boolCMDLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolCMDConsole {
            get {
                return ((bool)(this["boolCMDConsole"]));
            }
            set {
                this["boolCMDConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolRegistryLog {
            get {
                return ((bool)(this["boolRegistryLog"]));
            }
            set {
                this["boolRegistryLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolRegistryConsole {
            get {
                return ((bool)(this["boolRegistryConsole"]));
            }
            set {
                this["boolRegistryConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolProgramOpenedLog {
            get {
                return ((bool)(this["boolProgramOpenedLog"]));
            }
            set {
                this["boolProgramOpenedLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolProgramOpenedConsole {
            get {
                return ((bool)(this["boolProgramOpenedConsole"]));
            }
            set {
                this["boolProgramOpenedConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolGPLNoticeLog {
            get {
                return ((bool)(this["boolGPLNoticeLog"]));
            }
            set {
                this["boolGPLNoticeLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolGPLNoticeConsole {
            get {
                return ((bool)(this["boolGPLNoticeConsole"]));
            }
            set {
                this["boolGPLNoticeConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolStartupLog {
            get {
                return ((bool)(this["boolStartupLog"]));
            }
            set {
                this["boolStartupLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolStartupConsole {
            get {
                return ((bool)(this["boolStartupConsole"]));
            }
            set {
                this["boolStartupConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolWebsiteLog {
            get {
                return ((bool)(this["boolWebsiteLog"]));
            }
            set {
                this["boolWebsiteLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolWebsiteConsole {
            get {
                return ((bool)(this["boolWebsiteConsole"]));
            }
            set {
                this["boolWebsiteConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolSysInfoLog {
            get {
                return ((bool)(this["boolSysInfoLog"]));
            }
            set {
                this["boolSysInfoLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boolSysInfoConsole {
            get {
                return ((bool)(this["boolSysInfoConsole"]));
            }
            set {
                this["boolSysInfoConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting {
            get {
                return ((bool)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
